🎨 py-youwol/stop : log coverage report errors & do not fail step.

diff --git a/py-youwol/stop/action.yml b/py-youwol/stop/action.yml
--- a/py-youwol/stop/action.yml
+++ b/py-youwol/stop/action.yml
@@ -42,7 +42,7 @@ runs:
       working-directory: ${{ inputs.instance }}
       env:
         COVERAGE_DEBUG_FILE: coverage_html.debug
-      run: coverage html
+      run: coverage html 2> coverage_html.errors.log || echo "::error title=py-youwol coverage report::HTML generation failed. See job logs"
       shell: sh
 
     - name: Upload artifacts
